<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');


/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Enterprise Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/products/sugar-enterprise-eula.html
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2010 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/
	

$mod_strings = array (
  'LBL_ABOUT' => 'About',
  'LBL_ABOUT_HTML_COPY' => 'Copyright � 2004-2011',
  'LBL_ABOUT_HTML_RIGHTS' => 'All Rights Reserved',
  'LBL_ABOUT_HTML_SUGAR' => 'SugarCRM, Inc.',
  'LBL_ABOUT_HTML_TRADEMARK_1' => 'SugarCRM� e Sugar� sono',
  'LBL_ABOUT_HTML_TRADEMARK_2' => 'trademarks',
  'LBL_ABOUT_HTML_TRADEMARK_3' => 'of SugarCRM, Inc.',
  'LBL_ADDRESS' => 'Indirizzo',
  'LBL_ALL_ITEMS' => 'Tutti gli elementi',
  'LBL_ANDROID_PDF_INTENT_MISSING' => 'È necessario scaricare un visualizzatore di PDF.',
  'LBL_AUTHENTICATING' => 'Autenticazione',
  'LBL_AVAIL_ACTIONS' => 'Azioni Disponibili',
  'LBL_BAD_SUGAR_EDITIION' => 'Sugar Mobile può essere usato solo con Sugar Professional o Sugar Enterprise. Per saperne di più su Sugar si prega di visitare il sito http://www.sugarcrm.com o di registrarsi per una demo trial cliccando il pulsante di registrazione qui sotto.',
  'LBL_BAD_SUGAR_VERSION' => 'Sugar Mobile può essere usato con Sugar Enterprise o Sugar Professional dalla versione 6.2.0. L´URL inserito non corrisponde alle versioni supportate di Sugar Enterprise o Sugar Professional.',
  'LBL_CANCEL' => 'Annulla',
  'LBL_CANCEL_CHANGES' => 'Annulla le modifiche',
  'LBL_CHECK_NEW_RESOURCES' => 'In studio ci potrebbero essere degli aggiornamenti disponibili per il download, eseguire la sincronizzazione?',
  'LBL_CHOOSE_DATE' => 'Scegli una data',
  'LBL_CHOOSE_DATE_TIME' => 'Scegli una data/ora',
  'LBL_CLOSE' => 'Chiudi',
  'LBL_COMPLETE_ALL_FIELDS' => 'Si prega di completare tutti i campi richiesti.',
  'LBL_CONFIGURING' => 'Configurazione',
  'LBL_CONFIRM' => 'Conferma',
  'LBL_CONTINUE' => 'Continua',
  'LBL_CREATE' => 'Crea',
  'LBL_CREATE_NEW' => 'Crea Nuovo',
  'LBL_DELETE_PROMPT' => 'Eliminare questo record?',
  'LBL_DELETE_RECORD' => 'Elimina Record',
  'LBL_DELETING' => 'Eliminazione in corso...',
  'LBL_DETAIL' => 'Dettaglio',
  'LBL_DETAIL_VIEW' => 'Maschera Dettaglio',
  'LBL_DONE' => 'Fatto',
  'LBL_DOWNLOAD_PDF' => 'Scarica PDF',
  'LBL_EMAIL' => 'Email',
  'LBL_EMAIL_PDF' => 'Email PDF',
  'LBL_EMAIL_REPORT' => 'Report Email',
  'LBL_ENTER_CREDENTIALS' => 'Si prega di inserire le credenziali',
  'LBL_ENTER_VALID_URL' => 'Accertarsi di aver inserito un URL valido',
  'LBL_ERROR' => 'Errore',
  'LBL_FAVORITES' => 'Preferiti',
  'LBL_FREE_TRIAL' => 'Free Trial',
  'LBL_FREE_TRIAL_ERROR' => 'Impossibile procedere con la registrazione per la trial del mobile. Si prega di riprovare più tardi.',
  'LBL_FREE_TRIAL_MESSAGE' => 'Se sei un utente di Sugar Professional o Sugar Enterprise, seleziona Continua per accedere allo Sugar Mobile utilizzando le credenziali di Sugar. Seleziona Free Trial per accedere allo Sugar Mobile utilizzando un account trial.',
  'LBL_HELP' => 'Help',
  'LBL_HELP_HTML_ASSISTANCE' => 'Per assistenza, si prega di contattare',
  'LBL_HELP_HTML_SUPPORT' => 'SugarCRM Support',
  'LBL_IMPORT' => 'Importa',
  'LBL_IMPORT_ACCOUNT_MSSG' => 'E´ stato trovato il nome di un´azienda associato al tuo contatto. Vuoi creare un´azienda ugualmente?',
  'LBL_IMPORT_DESC' => 'Seleziona in quale modulo importare i contatti della rubrica del telefono. Dopo aver selezionato il modulo, sarà possibile selezionare un contatto dal tuo telefono e importarlo.',
  'LBL_IMPORT_DESC_SUBTITLE' => 'Nota: Una volta che un contatto è importato in Sugar, le eventuali modifiche apportate al record di Sugar non si rifletteranno nel contatto sul telefono.',
  'LBL_IMPORT_ERROR' => 'Si è verificato un errore durante l´importazione',
  'LBL_IMPORT_SUCCESSFUL' => 'Importazione eseguita con successo',
  'LBL_IMPRT_CONTACT' => 'Contatto',
  'LBL_IMPRT_LEAD' => 'Lead',
  'LBL_INVALID_CREDENTIALS' => 'Credenziali non valide. Si prega di riprovare.',
  'LBL_INVALID_VALUES' => 'Trovati valori non validi.',
  'LBL_LAST_VIEWED' => 'Ultima Vista',
  'LBL_LAST_VIEWED_NETWORK_ERROR' => 'Impossibile recuperare le ultime visualizzazioni. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_LIST' => 'Elenco',
  'LBL_LIST_ERROR' => 'Impossibile recuperare la vista elenco.',
  'LBL_LIST_NETWORK_ERROR' => 'Impossibile recuperare la lista. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_LOADING' => 'Caricamento...',
  'LBL_LOADING_LAYOUTS' => 'Caricamento Layout',
  'LBL_LOADING_MODULES' => 'Caricamento Moduli',
  'LBL_LOADING_TEAMS' => 'Caricamento Gruppi',
  'LBL_LOADING_USERS' => 'Caricamento Utenti',
  'LBL_LOGGING_CALL' => 'Registrazione Chiamata',
  'LBL_LOGIN' => 'Login',
  'LBL_LOGIN_ERROR' => 'Errore Login',
  'LBL_LOGIN_FAILED' => 'Login Fallito',
  'LBL_LOGOUT' => 'Logout',
  'LBL_LOG_CALL' => 'Nuova Chiamata',
  'LBL_LOG_CALL_ENTRY_DESC' => 'Record registrato automaticamente dal mobile',
  'LBL_LOG_CALL_ENTRY_TITLE' => 'Chiama dal mobile',
  'LBL_LOG_CALL_ERROR' => 'Si è verificato un errore durante la registrazione di una chiamata.',
  'LBL_LOG_CALL_TITLE' => 'Registrare questa chiamata?',
  'LBL_MODULES' => 'Moduli',
  'LBL_MY_ITEMS' => 'I miei elementi',
  'LBL_NEW_RECORD' => 'Nuovo Record',
  'LBL_NEW_SAVE_ERROR' => 'Impossibile salvare il record. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_NEXT' => 'Avanti',
  'LBL_NOT_AUTHORIZED' => 'Non sei autorizzato a vedere questo record',
  'LBL_NOT_AVAILABLE' => 'non disponibile',
  'LBL_NO_CALL_LOG' => 'Non registrare la chiamata',
  'LBL_NO_DATA' => 'Nessun dato trovato',
  'LBL_NO_RECORDS_FOUND' => 'Nessun record trovato',
  'LBL_OK' => 'OK',
  'LBL_OPEN_ACTIVITIES' => 'Attività Aperte',
  'LBL_OPEN_ACTIVITIES_NETWORK_ERROR' => 'Impossibile visualizzare le attività aperte. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_OPEN_CACHE_REPORT_ERROR' => 'Impossibile aprire report memorizzato nella cache',
  'LBL_PASSWORD' => 'Password',
  'LBL_PREVIOUS' => 'Indietro',
  'LBL_PULL_REFRESH' => 'Iconizza per aggiornare...',
  'LBL_PULL_RELOAD' => 'Pull to reload',
  'LBL_QUICK_VIEW' => 'Vista veloce',
  'LBL_RECORD_RETRIEVE_ERROR' => 'Impossibile recuperare il record. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_REFRESH' => 'Aggiorna',
  'LBL_REFRESHING' => 'Aggiornamento in corso',
  'LBL_REFRESH_SESSION' => 'Attivazione in corso',
  'LBL_REGISTER_LABEL' => 'Accedi allo Sugar Mobile usando un account di trial.',
  'LBL_REGISTRATION_SUCCESS' => 'Grazie per l&#39;avvenuta registrazione dell&#39;account trial per lo Sugar Mobile. Verrai automaticamente collegato.',
  'LBL_RELATED' => 'Collegato',
  'LBL_RELATED_ERROR' => 'Impossibile ottenere i dati correlati.',
  'LBL_RELEASED' => 'Released',
  'LBL_RELEASE_REFRESH' => 'Lancia per aggiornare...',
  'LBL_RELOADING' => 'Ricaricamento...',
  'LBL_REPORTS' => 'Report',
  'LBL_REPORT_ACCESS_DENIED' => 'Non sei in grado di accedere a questo report a causa delle restrizioni sui permessi',
  'LBL_REPORT_DOWNLOAD_ERROR' => 'Impossibile scaricare il report',
  'LBL_REPORT_DOWNLOAD_NETWORK_ERROR' => 'Impossibile scaricare il report. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_RETRIEVE_ERROR' => 'Impossibile recuperare il record.',
  'LBL_RETRIEVING_FILE' => 'Recupero File',
  'LBL_SAVE' => 'Salva',
  'LBL_SAVE_GENERIC_ERROR' => 'Errore imprevisto durante il salvataggio',
  'LBL_SAVE_NETWORK_ERROR' => 'Impossibile salvare il record. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_SAVE_RECORD' => 'Salva Record',
  'LBL_SAVING' => 'Salvataggio in corso...',
  'LBL_SEARCH' => 'Ricerca',
  'LBL_SEARCHING' => 'Ricerca in corso...',
  'LBL_SEARCH_FILTER' => 'Cerca filtro',
  'LBL_SEARCH_NETWORK_ERROR' => 'Impossibile eseguire la ricerca. La tua richiesta non può essere processata a causa di un timeout o un problema di connessione di rete.',
  'LBL_SEARCH_NO_RECORDS' => 'Nessun record trovato',
  'LBL_SEARCH_TIMEOUT' => 'Impossibile eseguire la ricerca. La tua richiesta non può essere processata a causa di un timeout o un problema di connessione di rete.',
  'LBL_SEARCH_TRY_AGAIN' => 'Si prega di rieseguire la ricerca.',
  'LBL_SELECT' => 'Seleziona',
  'LBL_SELECT_PDF_FORMAT' => 'Seleziona Formato PDF',
  'LBL_SETTINGS' => 'Impostazioni',
  'LBL_SET_DATE' => 'Imposta data',
  'LBL_SET_TIME' => 'Imposta ora',
  'LBL_SSL_CONN_ERROR' => 'Si è verificato un errore di elaborazione del certificato SSL fornito dal server.',
  'LBL_SSL_VALIDATE_CERT' => 'Consenti solo certificati Secure SSL',
  'LBL_SUBTITLE_NOT_AVAILABLE' => 'sottotitolo non disponibile',
  'LBL_SUCCESS' => 'Riuscito',
  'LBL_SUGAR_URL' => 'URL Sugar',
  'LBL_SYNCING' => 'Sincronizzazione',
  'LBL_SYNC_USERS_TEAMS' => 'Sync Utenti/Gruppi',
  'LBL_TAB_ABOUT' => 'About',
  'LBL_TAB_MODULES' => 'Moduli',
  'LBL_TAB_QUICK' => 'Vista veloce',
  'LBL_TAB_SEARCH' => 'Ricerca',
  'LBL_TITLE_NOT_AVAILABLE' => 'titolo non disponibile',
  'LBL_UNABLE_DISPLAY_PDF' => 'Impossibile visualizzare PDF.',
  'LBL_UNABLE_PROCESS_METADATA' => 'Impossibile elaborare i metadati del server.',
  'LBL_UNAUTHORIZED_ACCESS' => 'Non hai accesso a questa area. Contattare l´amministratore del sistema per ottenere i permessi.',
  'LBL_UPDATE_CREDENTIALS' => 'Aggiorna le credenziali',
  'LBL_USERNAME' => 'Nome Utente',
  'LBL_VERSION' => 'Versione',
  'LBL_VIEW' => 'Visualizza',
  'LBL_VIEW_PDF' => 'Visualizza PDF',
  'LBL_VIEW_RELATED' => 'Vedi Moduli Collegati',
  'LBL_VIEW_RELATED_ERROR' => 'Impossibile visualizzare i record correlati. La tua richiesta non può essere processata a causa di un timeout o problema di connessione di rete.',
  'LBL_VIEW_REPORT' => 'Visualizza Report',
  'LBL_VIEW_REPORT_PDF' => 'Visualizza Report PDF',
  'LBL_WARNING' => 'Avviso',
  'LBL_WEBSITE' => 'Sito web',
  'LBL_WELCOME' => 'Benvenuto',
);

